language: java
script: 
  - mvn clean package
deploy:
  provider: heroku
  api_key: a5ff1417-900e-4abe-a4f8-55055e6f9645
notifications:
  email:
    recipients:
      - lkawahara@student.neumont.edu
      - tdacus@student.neumont.edu
      - bauxer@student.neumont.edu
      - lringleka@student.neumont.edu
    on_failure: [always] # default: always