language: java
script: mvn clean package heroku:deploy-war
env:
  global: a5ff1417-900e-4abe-a4f8-55055e6f9645
notifications:
  email:
    recipients:
      - lkawahara@student.neumont.edu
      - tdacus@student.neumont.edu
      - bauxer@student.neumont.edu
      - lringleka@student.neumont.edu
    on_success: change
    on_failure: always